CREATE DATABASE LAB001
ON PRIMARY(
    NAME = LAB001,
    FILENAME = 'E:\code\sql\LUUTRU\LAB001.MDF',
    SIZE = 10MB,
    MAXSIZE = 100MB,
    FILEGROWTH =  1MB
)
LOG ON(
    NAME = LAB001_LOG,
    FILENAME = 'E:\code\sql\LUUTRU\LAB001_LOG.LDF',
    SIZE = 1MB,
    MAXSIZE = 100MB,
    FILEGROWTH = 1MB
)
-- CHECK XEM CO DB TEN LAB001 CHUA
SELECT NAME FROM sys.databases  WHERE NAME = 'LAB001'
-- DOI TEN DATABASE
ALTER DATABASE LAB001 MODIFY NAME = LAB001_TEST
-- SET VE CHE DO SINGLE_USER
ALTER DATABASE LAB001_TEST SET SINGLE_USER 

USE MASTER
GO

ALTER DATABASE LAB001_TEST SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DROP DATABASE LAB001_TEST